# Generated by Django 4.2.6 on 2023-10-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posts_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post/profile_images'),
        ),
    ]
